// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Maze","status":true,"description":"Simple raycasting engine which turns the game maps into 3D mazes.","parameters":{"resume":"Resume","retry":"Retry","quit":"Quit","yes":"Yes","no":"No","quality":"Quality","low":"Low","medium":"Medium","High":"High","auto":"Auto","block_width":"1","gen_floor":"2860","gen_wall":"6335","gen_tileset_id":"3"}}
];
